### ISSUE TITLE
Improve documentation management

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1293]
### Description
Define clear documentation GitHub branch management and release flow so that it can be automated.
Ideally, when a PR is merged into development branch, it is released into internal staging server, and when it is merged into main branch, it is automatically released to the production server.

### Motivation
Improve the GitHub and release management of the documentation so that the improvement and release flow are consistent and do not depend on any one person.

### Tasks

- [x] LiskHQ/lisk-service#1369
- [x] LiskHQ/lisk-service#1425 
- [x] Set up new branches following the migration plan

**Comment by shuse2** [comment]
These issues will be handled the Lisk core v4 updates
- https://github.com/LiskHQ/lisk-sdk/issues/6983
- https://github.com/LiskHQ/lisk-core/issues/577
- https://github.com/LiskHQ/lisk-docs/issues/1733

Moved to https://github.com/LiskHQ/lisk-docs/issues/1298 and https://github.com/LiskHQ/lisk-docs/issues/1297
