### ISSUE TITLE
Improve documentation for blockchain integrators

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1296]
### Description
Improve documentation for blockchain integration, such as API, transaction creation, tools to connect to a node, should be improved.

### Motivation
When updating the network, a lot of the questions are around blockchain integration.
In order to address these kind of questions, blockchain integration contents should be improved.

### Tasks

- [x] LiskHQ/lisk-docs#1428 
- [x] LiskHQ/lisk-docs#1258 
- [x] LiskHQ/lisk-docs#1262 
- [x] LiskHQ/lisk-docs#1578
- [x] LiskHQ/lisk-docs#1579
- [x] LiskHQ/lisk-docs#1580
- [x] LiskHQ/lisk-docs#1581
- [x] LiskHQ/lisk-docs#1582
- [x] LiskHQ/lisk-docs#1583
- [x] LiskHQ/lisk-docs#1584
- [x] LiskHQ/lisk-docs#1260 
- [x] LiskHQ/lisk-docs#1263
