### ISSUE TITLE
Update Lisk SDK documentation for version 6

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1297]
### Description
Update all existing Lisk SDK documentation including tutorials to be up to date with the interface and usage of the SDK.

### Motivation
Hack onl isk, grant program participants and sdk users should be able to use the latest version of the SDK as soon as possible. Additionally, existing developers should be able to upgrade existing applications or to start new applications with the latest interface.

#### Understand blockchain
- [x] #1488

##### Network
- [x] #1489

##### Consensus
- [x] #1492
- [x] Add `DPoS` - LiskHQ/lisk-docs#1245 

##### State machine
- [x] LiskHQ/lisk-docs#1495
- [x] LiskHQ/lisk-docs#1244 

##### SDK
- [x] LiskHQ/lisk-docs#1290 
- [x] LiskHQ/lisk-docs#1510
- [x] LiskHQ/lisk-docs#1511
- [x] LiskHQ/lisk-docs#1512
- [x] LiskHQ/lisk-docs#1513
- [x] LiskHQ/lisk-docs#1514
- [x] LiskHQ/lisk-docs#1515

##### Interoperability
- [x] LiskHQ/lisk-docs#1496
- [x] LiskHQ/lisk-docs#1516
- [x] LiskHQ/lisk-docs#1517

#### Build blockchain
- [x] LiskHQ/lisk-docs#1518
- [x] LiskHQ/lisk-docs#1647 
- [x] LiskHQ/lisk-docs#1520 
- [x] LiskHQ/lisk-docs#1523
- [x] LiskHQ/lisk-docs#1521
- [x] LiskHQ/lisk-docs#1524
- [x] LiskHQ/lisk-docs#1526
- [x] LiskHQ/lisk-docs#1519
- [x] LiskHQ/lisk-docs#1522
- [x] LiskHQ/lisk-docs#1525
- [x] LiskHQ/lisk-docs#1528
- [x] LiskHQ/lisk-docs#1529
- [x] LiskHQ/lisk-docs#1527

#### Run blockchain
- [x] LiskHQ/lisk-docs#1535
- [x] LiskHQ/lisk-docs#1531
- [x] LiskHQ/lisk-docs#1533
- [x] LiskHQ/lisk-docs#1534
- [x] LiskHQ/lisk-docs#1536
- [x] LiskHQ/lisk-docs#1532
- [x] LiskHQ/lisk-docs#1267 

#### APIs
- [x] LiskHQ/lisk-docs#1537
- [x] LiskHQ/lisk-docs#1538

#### Lisk SDK
- [x] LiskHQ/lisk-docs#1509
- [x] LiskHQ/lisk-docs#1491 
- [x] LiskHQ/lisk-docs#1540
- [x] LiskHQ/lisk-docs#1541
- [x] LiskHQ/lisk-docs#1542
- [x] LiskHQ/lisk-docs#1469
- [x] LiskHQ/lisk-docs#1543
- [x] LiskHQ/lisk-docs#1655 
- [x] LiskHQ/lisk-docs#1260
- [x] #1496

#### Others
- [x] LiskHQ/lisk-docs#1179 
- [x] LiskHQ/lisk-docs#1557
- [x] LiskHQ/lisk-docs#1673 
- [x] #1926
- [x] #1738
- [x] #1909
- [x] #1751 
- [x] #1517 
- [x] #1557
- [x] #1521
- [x] #1518
- [x] #1520
- [x] #1519 
- [x] #1513
- [x] #1516
- [x] #1538
- [x] #1488
- [x] #1469
- [x] #1495
- [x] #1492
- [x] #1487
- [x] #1728
- [x] #1858
- [x] #1867
- [x] #1543
- [x] #1263
- [x] #1847
- [x] #1827
- [x] #1879
- [x] #1267
- [x] #1905
- [x] #1796
- [x] #1260
- [x] #1891
- [x] #1678
- [x] #1260
- [x] #1883
- [x] #1880
- [x] #1871
- [x] #1868
- [x] #1824
- [x] #1828
- [x]  #1533
- [x] #1529
- [x] #1889
- [x] #1525
- [x] #1528
- [x] #1531
- [x] #1542
- [x] #1924
- [x] #1917
- [x] #1527
- [x] #1481
- [x] #1509
- [x] #1628
- [x] #1514
- [x] #1647
- [x] #1523
- [x] #1526
- [x] #1614
- [x] #1655
- [x] #1539
- [x]  #1510
- [x] #1511
- [x] #1512
- [x] #1290
- [x] #1537
- [x] #1540
- [x] #1541
- [x] #1179
- [x] #1658
- [x] #1708
- [x] #1534
- [x] #1739
- [x]  #1741
- [x] #1743
- [x] #1535
- [x] #1524
- [x] #1740
- [x] #1742
- [x] #1745
- [x] #1625
- [x] #1747
- [x] #1748
- [x] #1780
