### ISSUE TITLE
Update Lisk Core documentation for version 4

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1298]
### Description
Update all existing Lisk Coredocumentation including migration guide to be updated for the Lisk Core version 4

### Motivation
In order to release Lisk Core v4, all the documentation, especially node installation, API and public node information need to be updated.

#### Index

- [x] https://github.com/LiskHQ/lisk-core/issues/577
- [x] LiskHQ/lisk-docs#1559

#### Setup

- [x] LiskHQ/lisk-docs#1604
- [x] LiskHQ/lisk-docs#1605
- [x] LiskHQ/lisk-docs#1606

#### Management

- [x] LiskHQ/lisk-docs#1560
- [x] LiskHQ/lisk-docs#1561
- [x] LiskHQ/lisk-docs#1562
- [x] #1215

#### Update

- [x] LiskHQ/lisk-docs#1565

#### Reference

- [x] LiskHQ/lisk-core#743
- [x] LiskHQ/lisk-service#1266
