### ISSUE TITLE
Optimize command examples

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1490]
### Description

- ‘$’ should be removed in front of the commands https://lisk.com/documentation/lisk-core/management/configuration.html and other pages too.
- It would be better to see the command output on a different block.  https://lisk.com/documentation/lisk-core/management/account-management.html
- The callouts should be removed.
- Monospace should be removed. https://lisk.com/documentation/lisk-service/management/docker.html#start

Issues:

- [x] LiskHQ/lisk-docs#1827
- [x] LiskHQ/lisk-docs#1828
- [x] LiskHQ/lisk-service#1724
- [x] LiskHQ/lisk-core#796

### Affected versions
All `beta` versions
