### ISSUE TITLE
Update Lisk Service documentation for version 0.7

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1498]
### Description
Update all existing Lisk Service documentation including migration guide to be updated for the Lisk Service version 0.7.

### Motivation
In order to release Lisk service compatible with Lisk Core version 4, all the documentation, especially installation, API and public node information need to be updated.

### Tasks
- [x] https://github.com/LiskHQ/lisk-docs/issues/1733
- [x] LiskHQ/lisk-docs#1568
- [x] LiskHQ/lisk-docs#1569
- [x] LiskHQ/lisk-docs#1570
- [x] LiskHQ/lisk-docs#1571
- [x] LiskHQ/lisk-docs#1572
- [x] LiskHQ/lisk-docs#1573
- [x] LiskHQ/lisk-docs#1574
- [x] LiskHQ/lisk-docs#1575
- [x] LiskHQ/lisk-service#1541
- [x] LiskHQ/lisk-docs#1585
