### ISSUE TITLE
Update existing documentation with the new terminology

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1737]
### Description
The existing terminology regarding Lisk applications needs to be updated with the new terminology that we aligned on.

- [x] LiskHQ/lisk-docs#1738
- [x] LiskHQ/lisk-docs#1739
- [x] LiskHQ/lisk-docs#1740
- [x] LiskHQ/lisk-docs#1741
- [x] LiskHQ/lisk-docs#1742
- [x] LiskHQ/lisk-docs#1743
- [x] LiskHQ/lisk-docs#1745
- [x] LiskHQ/lisk-core#745

#### Affected branch / URL
`development`, `docs-sdk`, `docs-core`
