### ISSUE TITLE
Create getting started pages

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#199]
Create getting started pages for the Lisk documentation.

- [x] General Start page #200 
- [x] Interact with the network #201 
- [x] Maintain a node #202 
- [x] Build a blockchain application #203 
-  ~~How to contribute to the project~~
