### ISSUE TITLE
Workshop feedback

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#251]
- [x] https://github.com/LiskHQ/lisk-docs/blob/development/start/build-blockchain-app.md#2b-register-custom-transaction-types - wrong link #252 
- [x] script of sending a transaction has wrong name (fit structure in docs & github)#252
- [x] split up example app tutorials into several pages, explain what the 2 tutorials are about #252
- [x] add desired logs for last step of tutorial (verifying node has processed the tx)#252
- [x] add concrete software examples, how to make API requests on "interact with network" page #257 
- [x] Fix/ improve tutorial steps & code #262 
- [x] Explain in tutorials, how to verify, the tx got included with Lisk Commander/ API #262 
- ~~Create shorter tutorials that focus on code and commands~~
