### ISSUE TITLE
Review html page names

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#532]
## Which content is outdated?
Review, if the file names of the docs pages can be improved.
example: API specification has api.html, configuration has config.html, Create custom transaction types has customize.html, reference to refrerences.

- [x] Review file names in latest Core docs
- [x] Review file names in latest SDK docs
- [x] Review file names in 2.1.6 Core docs
