### ISSUE TITLE
Fix issues in latest Core docs

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#533]
- [x] Lisk Core product image is missing / Node, Peer should be small letters. Important at the top should be `click here` not `Click here`.
- [x] API, Mainnet API, Configuration is under Introduction.
- [x] Mainnet API doesn’t make sense. Only Betanet.
- [x] Setup>Binary/Source: All networks listed, but it’s not Testnet/Mainnet compatible
- [x] Setup>Commander: Note only 2.0 or higher. We are on 3.0 docs.
- [x] Setup>Docker/Source: Order of OS should always be the same. And Linux/Ubuntu should be decided upon.
- [x] Management. Lisk core, small c
- [x] Binary commands: Source Administration page doesn’t exist
- [x] Commander commands: Mainnet/Testnet even though its Betanet
- [x] Docker commands: URLs are written out
- [x] Source commands: Mainnet/Testnet
- [x] Handle config files: Docker Administration page doesn’t exist / Sometimes its Commander, sometimes Lisk Commander in the selection box
- [x] Enable forging: Lisk Commander, Cryptography module of Lisk Elements pages don’t exist 
- [x] Update>Binary: Important only 2.0 or higher. We are on 3.0 docs. / Mainnet/Testnet is in a different design. We are on Betanet
- [x] Update>Commander: Mainnet/Testnet
- [x] Update>Source: please see core releases should be Lisk Core releases
- [x] Migration: Lisk Node should be Lisk node. Migration for betanet? Mainnet/Testnet. Video: Lisk Core Successful Migration wrong proportions of the video
