### ISSUE TITLE
Fix issues in latest SDK docs

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#535]
- [x] Introduction: `The current version of the SDK is the alpha release stage.` should be `The Lisk SDK is currently in alpha stage`. And always call it Lisk SDK, not only SDK.
- [x] Prerequisites: Ubuntu/macOS, there should be an order. And either Linux or Ubuntu.
- [x] Guides: There is a typo: Hello Word.
- [x] Create custom transaction types: Plural why not singular `Add a custom transaction`? The Store what is the store? Maybe storage component?
- [x] Test transaction types: Plural, why not singular? `Test a custom transaction`
- [x] Interact with the network > Interact with the API
- [x] Broadcast transactions > Broadcast a transaction. Should it be before `Interact with the network` in the navigation?
- [x] Connect a frontend: Say that we recommend React and put it first in the list. .
- [x] Tutorials: We say Supply Chain, but in the navigation Supply chain.
- [x] Tutorials>Hello world. Difference to the guides? I think we discussed once that this should then be removed.
- [x] Reference: Weird first list. Commander, Commands, Core commands
- [x] Reference>API specification: With the specification or only API?
- [x] Reference>Lisk Commander>Lisk Core commands: I don’t see the reason to have it here. Should be in the Lisk Core documentation.
- [x] Reference>Lisk Elements: In the package list under Specification not sure about the `docs` after each package name.
- [x] Reference>Lisk Elements>API client>DApps: Does it still exist, wasn’t it deactivated?
- [x] Reference>Lisk Elements>Client. The wording is not nice. `This provides a default set of elements for use..`
- ..>P2P: Library..
- ..>Passphrase: `Lisk elements passphrase module`..
- >Transaction pool: Library and not a dot.
- >Transactions: Module
- >Validator: Wrapper of validation libraries
- >> Should all be changed to package
