### ISSUE TITLE
Fix issues in current Core docs 2.1.5

### ISSUE THREAD

**Issue by chris529** [LiskArchive/lisk-legacy-docs#591]
- [x]  Lisk Core product image is missing / Node, Peer should be small letters. Important at the top should be click here not Click here.
- [x]  Mainnet API doesn’t make sense. Only Betanet.
- [x] Setup>Binary/Source: All networks listed, but it’s not Testnet/Mainnet compatible
- [x]  Setup>Commander: Note only 2.0 or higher. We are on 3.0 docs.
- [x] Setup>Docker/Source: Order of OS should always be the same. And Linux/Ubuntu should be decided upon.
- [x] Management. Lisk core, small c
 - [x] Binary commands: Source Administration page doesn’t exist
- [x]  Docker commands: URLs are written out
- [x]  Source commands: Mainnet/Testnet
- [x] Handle config files: Docker Administration page doesn’t exist / Sometimes its Commander, sometimes Lisk Commander in the selection box
- [x]  Enable forging: Lisk Commander, Cryptography module of Lisk Elements pages don’t exist
 - [x] Migration: Lisk Node should be Lisk node. Migration for betanet? Mainnet/Testnet. Video: Lisk Core Successful Migration wrong proportions of the video
- [x]  2.1.5  'Config file handling' instead of 'Handle config files' - mirror ver. 3.0.0 
- [x]  2.1.5 Mainnet first then Testnet (in Navigation)
