### ISSUE TITLE
Review of the existing documentation

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#665]
The whole documentation needs to be reviewed after all the structural changes and additions that have been added lately.

-  [x] Review Core 2.1.6 docs
-  [x] Review Core 3.0.0 docs
-  [x] Review SDK 3.0.2 docs
