### ISSUE TITLE
Improve links in the documentation

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#749]
**Is your feature request related to a problem? Please describe.**
Sometimes link labels are confusing and they are not indicating where exactly  the link is leading .

**Describe the solution you'd like**
 
A standard for link labels should be developed, that helps indicating where the link is taking the user.

There should be link label guidelines for:

- external links, indicating it is external, and to which page it is going, e.g. GitHub.
- links to other docs-components
- links to other pages
- links on the same page

These guidelines then need to be applied in all latest documentations.

- [ ] Create guidelines for links in the documentation
- [ ] Apply for latest Lisk SDK docs
- [ ] Apply for latest Lisk Service docs
- [ ] Apply for latest Lisk Core docs

**Comment by Tschakki** [comment]
See: https://developers.google.com/style/link-text
